### ISSUE TITLE
清除浮动的方式

### ISSUE THREAD

**Issue by Huai-Kang** [Feel-Joy/awsome-front-end-questions#9]
列举清除浮动的几种方式。

**Comment by Huai-Kang** [comment]
* 在父元素末尾新增块级元素，应用以下样式：
```css
.clear {
 clear: both;
}
```
* 使用父元素的伪类，并应用以下样式：
```css
.clear:after {
 content: '';
 clear: both;
 display: block;
 visibility: hidden;
}
```
* 为父元素新增以下样式：
```css
.clear {
 overflow: auto;
 /* overflow: hidden 也可以实现，但可能不利于SEO */
}
```
